syntax = "proto3";

package oryon.identity.v1;

// ========
// services
// ========

service AuthenticationService {
  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc Logout(LogoutRequest) returns (LogoutResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
}

// =====
// enums
// =====

// ======
// models
// ======

message Token {
  string access_token = 1;
  string refresh_token = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  Token token = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {}

message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  Token token = 1;
}
